version: '2.2'

services:


  dbmysql:
    image: mysql
    restart: always
    ports:  
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=Print
      - MYSQL_ROOT_PASSWORD='Print1234'
      - MYSQL_USER=smit
      - MYSQL_PASSWORD=smit1234
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
      - ./mysql_db_data_container:/var/lib/mysql
    networks:
      - print

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: dbmysql
      ADMINER_DESIGN: pepa-linha
    links:
      - dbmysql

  appl:
    # dockerfile: Dockerfile
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    links:
      - dbmysql
    networks:
      - print
        
networks:
  print:
    driver: bridge
